using System.Text;

namespace CoffeeBean.EditorTools
{
    /// <summary>
    /// 面板生成信息（收集自预制体上的 CBind 标记）：
    /// 供模板生成字段声明与 ClearUIComponents 清理代码。
    /// </summary>
    internal sealed class CUIPanelCodeInfo
    {
        /// <summary>单个绑定字段信息。</summary>
        public sealed class BindField
        {
            /// <summary>字段名（默认节点名）。</summary>
            public string FieldName;

            /// <summary>组件类型名（如 UnityEngine.UI.Button）。</summary>
            public string ComponentType;

            /// <summary>字段注释（CBind.Comment）。</summary>
            public string Comment;

            /// <summary>是否为独立 CUIElement（生成独立脚本）。</summary>
            public bool IsElement;
        }

        public System.Collections.Generic.List<BindField> Fields = new System.Collections.Generic.List<BindField>();
    }

    /// <summary>
    /// 面板代码模板：
    /// 主脚本（用户可编辑，仅首次生成）+ Designer partial（自动生成，可反复覆盖）。
    /// </summary>
    internal static class CUICodeTemplates
    {
        /// <summary>生成主脚本（仅当文件不存在时，避免覆盖用户代码）。</summary>
        public static string PanelMainScript(string panelName, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine("using CoffeeBean;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>{panelName} 面板数据。</summary>");
            sb.AppendLine($"    public class {panelName}Data : CUIPanelData");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {panelName} 面板（自动生成主脚本，可自由编辑）。");
            sb.AppendLine("    /// 字段绑定见 {panelName}.Designer.cs（自动生成，请勿手改）。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public partial class {panelName} : CUIPanel");
            sb.AppendLine("    {");
            sb.AppendLine($"        private {panelName}Data _data;");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnInit(ICUIData uiData = null)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _data = uiData as {panelName}Data ?? new {panelName}Data();");
            sb.AppendLine("            // TODO: 初始化逻辑");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnOpen(ICUIData uiData = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 每次打开逻辑");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnShow()");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 显示逻辑");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnHide()");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 隐藏逻辑");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnClose()");
            sb.AppendLine("        {");
            sb.AppendLine("            // TODO: 关闭逻辑");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>生成 Designer partial（字段 + ClearUIComponents，每次覆盖）。</summary>
        public static string PanelDesignerScript(string panelName, string ns, CUIPanelCodeInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// 此文件由 CoffeeBean UI 代码生成器自动生成，请勿手动修改（重新生成会覆盖）。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using CoffeeBean;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>自动生成：字段绑定与清理（partial 主脚本见 {panelName}.cs）。</summary>");
            sb.AppendLine($"    public partial class {panelName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string Name = \"{panelName}\";");
            sb.AppendLine();

            foreach (var field in info.Fields)
            {
                if (!string.IsNullOrEmpty(field.Comment))
                {
                    sb.AppendLine("        /// <summary>" + field.Comment + "</summary>");
                }
                sb.AppendLine($"        [SerializeField] public {field.ComponentType} {field.FieldName};");
            }

            sb.AppendLine();
            sb.AppendLine("        protected override void OnBeforeDestroy()");
            sb.AppendLine("        {");
            sb.AppendLine("            ClearUIComponents();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private void ClearUIComponents()");
            sb.AppendLine("        {");
            foreach (var field in info.Fields)
            {
                sb.AppendLine($"            {field.FieldName} = null;");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>生成独立 CUIElement 脚本（CBind.IsElement = true 时）。</summary>
        public static string ElementScript(string elementName, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using CoffeeBean;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>{elementName} 元素（自动生成，可编辑）。</summary>");
            sb.AppendLine($"    public class {elementName} : CUIElement");
            sb.AppendLine("    {");
            sb.AppendLine("        // TODO: 元素逻辑");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
